[package]
edition = "2021"
name = "transaction-consumer"
version = "0.17.1"

[dependencies]
anyhow = "1"
futures = "0.3"
log = "0.4.14"
rdkafka = { version = "0.36.2", features = ["gssapi", "sasl", ] }
url = "2.2.2"
tokio = { version = "1.17", features = ["sync", "fs", "rt", "macros"] }

nekoton = { git = "https://github.com/broxus/nekoton.git", default-features = false }
nekoton-abi = { git = "https://github.com/broxus/nekoton.git" }

ton_abi = { git = "https://github.com/broxus/ton-labs-abi" }
ton_block = { git = "https://github.com/broxus/ton-labs-block" }
ton_types = { git = "https://github.com/broxus/ton-labs-types" }

everscale-rpc-client = { git = "https://github.com/broxus/everscale-jrpc.git" }
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"

[features]
vendored = ["rdkafka/gssapi-vendored"]
default = ["vendored"]


[target.'cfg(target_os = "macos")'.dependencies.rdkafka]
features = ["gssapi-vendored", "sasl"]
version = "0.36.2"
